# https://sw.kovidgoyal.net/kitty/conf/

# theme
# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME

# tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style round

# window
window_margin_width 4
macos_titlebar_color background

# font
font_family SF Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 14.0

# other
macos_quit_when_last_window_closed yes
mouse_hide_wait 3.0

# defaults
editor nano
# shell fish --login --interactive

# scrolling
scrollbar scrolled
scrollbar_interactive yes
scrollbar_jump_on_click no
